# -*- coding: utf-8 -*-
"""Tree-DSA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17tQSvsURlSovCfZiUkkBFyo5xShInHEP

# **TREE DATA STRUCTURE** 🎄
"""

class Node:
    def __init__(self, item):
        self.left = None
        self.right = None
        self.val = item


def inorder(root):    # Left -- Root -- Right (pattern)

    if root:
        # Traverse left
        inorder(root.left)
        # Traverse root
        print(str(root.val) + "->", end='')
        # Traverse right
        inorder(root.right)


def postorder(root):       # Left -- Right -- Root

    if root:
        # Traverse left
        postorder(root.left)
        # Traverse right
        postorder(root.right)
        # Traverse root
        print(str(root.val) + "->", end='')


def preorder(root):       # Root -- Left -- Right

    if root:
        # Traverse root
        print(str(root.val) + "->", end='')
        # Traverse left
        preorder(root.left)
        # Traverse right
        preorder(root.right)


root = Node(1)
root.left = Node(2)
root.right = Node(3)
root.left.left = Node(4)
root.left.right = Node(5)
root.right.right = Node(6)

print("Inorder traversal ")
inorder(root)

print("\nPreorder traversal ")
preorder(root)

print("\nPostorder traversal ")
postorder(root)

"""## **Tree Image:**🌴
Pictorial form of the above tree code implementation.
"""

pip install Pillow

from PIL import Image

# Assuming the image is named 'TREE.structure1.png' and is in the content directory
image_path = '/content/TREE.structure1.png'

try:
    img = Image.open(image_path)
    display(img)
except FileNotFoundError:
    print(f"Error: The file '{image_path}' was not found. Please ensure it's uploaded correctly.")
except Exception as e:
    print(f"An error occurred: {e}")