# -*- coding: utf-8 -*-
"""Binary Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbuhyKQxaTV_6kSkymgeWrh5NS6TPJ1o

# **BINARY TREE IMPLEMENTATION:**🌴
"""

class Node:
  def __init__(self,data):
    self.data=data
    self.left=None
    self.right=None

  def insert(self, data):
     queue = [self]

     while queue:
           current = queue.pop(0)

           if current.left is None:
              current.left = Node(data)
              return

           else:
              queue.append(current.left)

           if current.right is None:
             current.right = Node(data)
             return

           else:
             queue.append(current.right)

  def level_order_traversal(self):
    if not self:
      print("Tree is empty")
      return

    q = [self]
    result = []
    while q:
      node = q.pop(0)
      result.append(node.data)

      if node.left:
        q.append(node.left)
      if node.right:
        q.append(node.right)
    print("Tree elements (level-order traversal):")
    print(result)


root = Node(1)
root.insert(2)
root.insert(3)
root.insert(4)

root.level_order_traversal()

"""## **Delete Method:**📤"""

class Node:
  def __init__(self,data):
    self.data=data
    self.left=None
    self.right=None

# Function to delete the deepest node (d_node) from the tree rooted at root
def delete_deepest(root, d_node):
    q = [root]
    while q:
        curr = q.pop(0)
        # If the current node itself is the deepest node (e.g., if root is the only node)
        if curr == d_node:
            # This case ideally should not happen if d_node is a child node,
            # but handles cases where root itself might be the deepest.
            # However, direct assignment to None won't remove it from parent's reference.
            # The deletion from parent's reference is handled below.
            return
        if curr.right:
            if curr.right == d_node:
                curr.right = None
                return
            else:
                q.append(curr.right)
        if curr.left:
            if curr.left == d_node:
                curr.left = None
                return
            else:
                q.append(curr.left)

# Function to perform deletion in a binary tree
def deletion(root, key):
    if not root:
        return None

    # Handle case where root itself is the node to be deleted and it's a leaf
    if root.left is None and root.right is None:
        if root.data == key:
            return None
        else:
            return root

    q = [root]
    node_to_delete = None # Node with the key to be deleted
    deepest_node = None # Last node encountered (deepest and rightmost in BFS)

    while q:
        temp = q.pop(0)
        deepest_node = temp # Keep track of the deepest node encountered

        if temp.data == key:
            node_to_delete = temp # Found the node to be deleted

        if temp.left:
            q.append(temp.left)
        if temp.right:
            q.append(temp.right)

    if node_to_delete: # If the node with the key was found
        # Replace data of the node to be deleted with the data of the deepest node
        node_to_delete.data = deepest_node.data
        # Delete the deepest node from its original position
        delete_deepest(root, deepest_node)

    return root

# Inorder traversal function
def inorder(curr):
  if curr is None:
    return
  inorder(curr.left)
  print(curr.data, end=" ")
  inorder(curr.right)

if __name__ == '__main__':
  root = Node(1)
  root.left = Node(2)
  root.right = Node(3)
  root.left.left = Node(4)

  key_to_delete = 2
  root = deletion(root, key_to_delete)

  print("Inorder traversal of the modified tree:")
  inorder(root)

"""## **SEARCH METHOD:**📡"""

class Node:
  def __init__(self,data):
    self.data=data
    self.left=None
    self.right=None

  def search(self, value):
     if self.data == value:
         return True

     if self.left:
        if self.left.search(value):
          return True

     if self.right:
        if self.right.search(value):
          return True
     return False

root = Node(1)
root.left = Node(2)
root.right = Node(3)
root.left.left = Node(4)

#VALUE_TO_SEARCH
value_to_search = 5
result = root.search(value_to_search)
print(result)